name: Release PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Set up LaTeX
        uses: dante-ev/latex-action
        with:
          root_file: main.tex

      - name: Compile LaTeX document
        run: |
          latexmk -xelatex -shell-escape -interaction=nonstopmode -file-line-error CPP-Concurrency-In-Action-2ed-2019.tex

      - name: Upload PDF to release
        uses: softprops/action-gh-release@v1
        with:
          files: CPP-Concurrency-In-Action-2ed-2019.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
